### ISSUE TITLE
Comment some lines?

### ISSUE THREAD

**Issue by cschaf** [powerbq/IdeaKeygenGui#1]
Thanks man, thats really helped me. Maybe you could explain some lines of your code, especially die MakeKey function?

**Comment by powerbq** [comment]
Hi, you welcome.
The author of this methods is "vhsousa", but it was only command line solution. I just added gui and assigned this methods to gui for get user friendly interface.
What are you not understand in code of this method?

**Comment by cschaf** [comment]
Whats the "bkey" values in MakeKey come from and what do they mean?
